//endpoints//

###
POST http://localhost:9000/api/areas HTTP/1.1
Content-Type: application/json

{
    "nombre_area": "verdurero"
}

###
GET http://localhost:9000/api/areas HTTP/1.1

###
GET http://localhost:9000/api/areas/67365b2d754769c34070a38c HTTP/1.1

###
PUT http://localhost:9000/api/areas/673abdd09fdeac8a7ba46997 HTTP/1.1
Content-Type: application/json

{
    "nombre_area": "Área de Prueba Actualizada"
}

###
DELETE http://localhost:9000/api/areas/ID_DE_AREA HTTP/1.1


// request.http

###
POST http://localhost:9000/api/recursos HTTP/1.1
Content-Type: application/json

{
    "nombre_recurso": "Sillas",
    "cantidad": 50,
    "ubicacion": "Almacén A"
}

###
GET http://localhost:9000/api/recursos HTTP/1.1

###
GET http://localhost:9000/api/recursos/{id} HTTP/1.1

###
PUT http://localhost:9000/api/recursos/{id} HTTP/1.1
Content-Type: application/json

{
    "nombre_recurso": "Mesas",
    "cantidad": 30,
    "ubicacion": "Almacén B"
}

###
DELETE http://localhost:9000/api/recursos/{id} HTTP/1.1

###
POST http://localhost:9000/api/horarios HTTP/1.1
Content-Type: application/json

{
    "id_empleado": "648d29f0e4f4a8cce401b1f1",
    "dia_semana": "Lunes",
    "hora_entrada": "08:00",
    "hora_salida": "16:00"
}

###
GET http://localhost:9000/api/horarios HTTP/1.1

###
GET http://localhost:9000/api/horarios/{id} HTTP/1.1

###
PUT http://localhost:9000/api/horarios/{id}
Content-Type: application/json

{
    "id_empleado": "648d29f0e4f4a8cce401b1f1",
    "dia_semana": "Lunes",
    "hora_entrada": "09:00",
    "hora_salida": "17:00"
}


###
DELETE http://localhost:9000/api/horarios/{id} HTTP/1.1


###
POST http://localhost:9000/api/beneficios HTTP/1.1
Content-Type: application/json

{
    "id_empleado": "648d29f0e4f4a8cce401b1f1",
    "monto": 500000,
    "fecha": "2024-12-03"
}

###
GET http://localhost:9000/api/beneficios HTTP/1.1


###
GET http://localhost:9000/api/beneficios/{id} HTTP/1.1

###
PUT http://localhost:9000/api/beneficios/{id} HTTP/1.1
Content-Type: application/json

{
    "id_empleado": "648d29f0e4f4a8cce401b1f1",
    "monto": 600000,
    "fecha": "2024-12-10"
}

###
DELETE http://localhost:9000/api/beneficios/{id} HTTP/1.1

###
POST http://localhost:9000/api/cliente HTTP/1.1
Content-Type: application/json

{
    "nombre_cliente": "dironxde",
    "telefono": "3235534567",
    "email": "xde@email.com"
}

###
GET http://localhost:9000/api/cliente HTTP/1.1

###
GET http://localhost:9000/api/cliente/674f031ea7578b79399b5fb7 HTTP/1.1

###
PUT http://localhost:9000/api/cliente/674f031ea7578b79399b5fb7 HTTP/1.1
Content-Type: application/json

{
    "nombre_cliente": "Juan Pérez Gómez",
    "telefono": "3009876543",
    "email": "juanperezgomez@email.com"
}

###
DELETE http://localhost:9000/api/cliente/674f031ea7578b79399b5fb7 HTTP/1.1


###
POST http://localhost:9000/api/evento HTTP/1.1
Content-Type: application/json

{
    "fecha_evento": "2024-12-10",
    "descripcion": "xddeee xdee xdeee",
    "cliente_id": "674f034ca7578b79399b5fbc"
}

###
GET http://localhost:9000/api/evento HTTP/1.1

###
GET http://localhost:9000/api/evento/674f05f9c14925c50bfa7bcb HTTP/1.1

###
PUT http://localhost:9000/api/evento/674f05f9c14925c50bfa7bcb HTTP/1.1
Content-Type: application/json

{
    "fecha_evento": "2024-12-11",
    "descripcion": "no es de  xdeee",
    "cliente_id": "674f034ca7578b79399b5fbc"
}

###
DELETE http://localhost:9000/api/evento/674f05f9c14925c50bfa7bcb HTTP/1.1
